config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users',
    sessions: 'users/sessions',
    omniauth_callbacks: 'callbacks' 
  } 

  resources :users do
    resources :custom_fields
  end
  root "home#index" 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid email format" }
  validates :password, presence: true
  validates :mobile_number, presence: true, format: { with: /\A\d{10}\z/, message: "Invalid mobile number format" } 

  has_many :custom_fields, dependent: :destroy
  accepts_nested_attributes_for :custom_fields

  class << self
    def create_new(inputs)
      user_inputs = inputs.slice(:name, :email, :password, :mobile_number)
      user = User.new(user_inputs)
      user.save!

      return { success: true, user: user}
    end
  end #__End of class << self

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user |
    user.provider = auth.provider
    user.name = auth.info.name
    user.uid = auth.uid
    user.email = auth.info.email
    user.mobile_number = '8009001000'
    user.password = Devise.friendly_token[0,20]
    end
  end

  def create_custom_fields(inputs)
    CustomField.create_new(inputs, self)
  end
  
  def update_profile(inputs)
    user_inputs = inputs.permit(:name, :email, :password, :mobile_number)
    self.update!(user_inputs)
 
    { success: true, user: self }
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :redirect_signed_in_user, only: [:new]
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  private
  def redirect_signed_in_user
    redirect_to root_path if user_signed_in?
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
    @user.custom_fields.build
  end

  def create
    rv = User.create_new(user_params)
    if (rv[:error])
      render :rv
    end

    @user = rv[:user]
    sign_in(@user)
    redirect_to @user, notice: 'User was successfully created.'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    rv = @user.update_profile(user_params)
    if (rv[:error])
      render :edit
    end

    @user = rv[:user]
    redirect_to @user, notice: 'User was successfully updated.'
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :mobile_number)
  end

  def authorize_user!
    unless current_user == User.find(params[:id])
      redirect_to root_path, alert: "You don't have permission to do that."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_custom_field.html.erb
 <h2>Custom Fields</h2>
  <ul>
    <% @user.custom_fields.each do |custom_field| %>
      <li>
        <strong><%= custom_field.field_name %>:</strong> <%= custom_field.default_value %> 
        <% if current_user == @user %>
          <%= link_to 'Edit', edit_user_custom_field_path(@user, custom_field) %>
          <%= button_to 'Delete', user_custom_field_path(@user, custom_field), method: :delete, form: { data: { turbo_confirm: 'Are you sure?'}} %>
        <% end %>
      </li>
    <% end %>
  </ul>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Email: <%= form.text_field :email %></p>
  <p>Password: <%= form.password_field :password %></p>
  <p>Mobile Number: <%= form.text_field :mobile_number %></p>

  <%= link_to "List Custom Fields", user_custom_fields_path(@user) %>
  <p><%= form.submit %></p>
<% end %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Email: <%= form.text_field :email %></p>
  <p>Password: <%= form.password_field :password, required: true %></p>
  <p>Mobile Number: <%= form.text_field :mobile_number %></p>
  <p><%= form.submit %></p> 
<% end %>

<%= render 'custom_field' %>
<%= link_to 'Add Custom Field', new_user_custom_field_path(@user)%>
<%= link_to 'Back', user_path(@user) %> 

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile Number</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.mobile_number %></td>
        <td>
          <%= link_to 'Show', user %>
          <% if current_user == user %>
            <%= link_to 'Edit', edit_user_path(user) %>
            <%= button_to "Destroy", user_path(user), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', root_path %> 
<% if user_signed_in? %>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to "Sign In", new_user_session_path %>
<% end %>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>New User</h1>
<%= form_with(model: @user, local: true) do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Email: <%= form.text_field :email %></p>
  <p>Password: <%= form.password_field :password %></p>
  <p>Mobile Number: <%= form.text_field :mobile_number %></p>
  <p><%= form.submit %></p>
<% end %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>
<p>Mobile Number: <%= @user.mobile_number %></p>

<% if @user.custom_fields.present? %>
 <%= render 'custom_field' %>
<% end %>

<%= link_to 'Back', users_path %> 
<% if current_user == @user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Add Custom Field', new_user_custom_field_path(@user)%>
<% end %>

<% if user_signed_in? %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
 <%= button_to "Sign In", new_user_session_path %> 
<% end %>